packages:
  - 'apps/electron/example-basic'
  - 'apps/electron/example-handlers'
  - 'apps/electron/example-reducers'
  - 'apps/tauri/example-reducers'
  - 'apps/tauri/example-separate-handlers'
  - 'apps/tauri/example-store-handlers'
  - 'apps/tauri-v1/example-reducers'
  - 'apps/tauri-v1/example-separate-handlers'
  - 'apps/tauri-v1/example-store-handlers'
  - 'e2e'
  - 'packages/electron'
  - 'packages/tauri'
  - 'packages/tauri-v1'
  - 'packages/types'
  - 'packages/core'
