packages:
  - 'apps/minimal-zustand-basic'
  - 'apps/minimal-custom'
  - 'apps/minimal-redux'
  - 'apps/minimal-zustand-handlers'
  - 'apps/minimal-zustand-reducers'
  - 'apps/e2e-electron'
  - 'apps/e2e-tauri'
  - 'apps/e2e-tauri-v1'
  - 'e2e'
  - 'packages/apps-shared'
  - 'packages/core'
  - 'packages/electron'
  - 'packages/middleware/node'
  - 'packages/tauri'
  - 'packages/tauri-plugin'
  - 'packages/types'
  - 'packages/ui'
