packages:
  - 'apps/electron-example'
  - 'apps/tauri-example'
  - 'apps/tauri/example-reducers'
  - 'apps/tauri/example-handlers'
  - 'apps/tauri/example-basic'
  - 'e2e'
  - 'packages/electron'
  - 'packages/tauri'
  - 'packages/types'
  - 'packages/core'
