packages:
  - 'apps/electron/minimal-zustand-basic'
  - 'apps/electron/minimal-zustand-handlers'
  - 'apps/electron/minimal-zustand-reducers'
  - 'apps/electron/minimal-redux'
  - 'apps/electron/minimal-custom'
  - 'apps/electron/minimal-zustand-immer'
  - 'apps/electron/manual-context-isolation-false'
  - 'apps/electron/e2e'
  - 'apps/tauri/e2e'
  - 'apps/tauri-v1/e2e'
  - 'e2e'
  - 'packages/apps-shared'
  - 'packages/core'
  - 'packages/electron'
  - 'packages/middleware/node'
  - 'packages/tauri'
  - 'packages/tauri-plugin'
  - 'packages/types'
  - 'packages/ui'
