packages:
  - 'apps/electron/example-reducers'
  - 'apps/electron/example-separate-handlers'
  - 'apps/electron/example-store-handlers'
  - 'apps/tauri/example-reducers'
  - 'apps/tauri/example-separate-handlers'
  - 'apps/tauri/example-store-handlers'
  - 'e2e'
  - 'packages/zubridge-electron'
  - 'packages/zubridge-tauri'
