name: 'Handle E2E Test Failures'
description: 'Uploads logs and enables debugging on E2E test failure'
inputs:
  os:
    description: 'Operating system of the runner'
    required: true
  app:
    description: 'Type of application (electron, tauri, tauri-v1)'
    required: true
  mode:
    description: 'Application mode (basic, handlers, etc.)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Show Test Logs
      if: inputs.app == 'electron'
      run: cat ./e2e/wdio-logs-${{ inputs.app }}-${{ inputs.mode }}/*.log || echo "No log files found"
      shell: bash

    - name: Upload Test Logs
      uses: actions/upload-artifact@v4
      if: inputs.app == 'electron'
      with:
        name: e2e-logs-${{ inputs.os }}-${{ inputs.app }}-${{ inputs.mode }}
        path: e2e/wdio-logs-${{ inputs.app }}-${{ inputs.mode }}/*.log
        retention-days: 30
        if-no-files-found: warn
