name: 'Handle E2E Failures'
description: 'Show logs and upload artifacts on test failure'

inputs:
  os:
    description: "Operating system tests ran on"
    required: true
  app:
    description: "Type of application tested"
    required: true
  mode:
    description: "Test mode"
    required: true

runs:
  using: "composite"
  steps:
    - name: Show Test Logs
      if: inputs.app == 'electron'
      run: cat ./e2e/wdio-logs-${{ inputs.app }}-${{ inputs.mode }}/*.log || echo "No log files found"
      shell: bash

    - name: Upload Test Logs
      uses: actions/upload-artifact@v4
      if: inputs.app == 'electron'
      with:
        name: e2e-logs-${{ inputs.os }}-${{ inputs.app }}-${{ inputs.mode }}
        path: e2e/wdio-logs-${{ inputs.app }}-${{ inputs.mode }}/*.log
        retention-days: 30
        if-no-files-found: warn
