description: 'Sets up Node.js environment with PNPM for CI/CD workflows'
inputs:
  node-version:
    description: 'Node.js version to use (e.g., "20")'
    required: true
  registry-url:
    description: 'Registry URL to use for npm'
    required: false
    default: 'https://registry.npmjs.org'

runs:
  using: composite
  steps:
    - name: 🧰 Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        run_install: false
        version: 10

    - name: 🛠️ Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'

    - name: ⚙️ Set PNPM store path
      shell: bash
      run: |
        pnpm config set store-dir ~/.pnpm-store --global

    - name: ⚙️ Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: 🔧 Configure Git identity
      shell: bash
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
