[package]
name = "zubridge-tauri-v1"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "zubridge_tauri_v1"
path = "src-rust/lib.rs"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
