[package]
name = "zubridge-backend-core"
version = "0.1.0"
edition = "2021"
description = "A helper crate for Zubridge Tauri backend state management"
license = "MIT"
repository = "https://github.com/goosewobbler/zubridge"

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["sync"], optional = true }

[features]
default = []
tokio = ["dep:tokio"]

[dev-dependencies]
tokio-test = "0.4"
