[package]
name = "tauri-plugin-zubridge"
version = "0.1.0"
description = "A Tauri plugin for state management between frontend and backend"
authors = ["Sam Maister"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.70"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-zubridge"

[dependencies]
tauri = { version = "2.0.0-beta" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
log = "0.4"

[build-dependencies]
tauri-build = { version = "2.0.0-beta" }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
