name: 'Install Tauri Dependencies'
description: 'Installs platform-specific dependencies required for Tauri builds'

inputs:
  app_type:
    description: "Type of Tauri application (tauri or tauri-v1)"
    required: true
    default: "tauri"

runs:
  using: "composite"
  steps:
    # Linux-specific dependencies
    - name: Install Linux Dependencies
      if: runner.os == 'Linux' && (inputs.app_type == 'tauri' || inputs.app_type == 'tauri-v1')
      shell: bash
      run: |
        sudo tee -a /etc/apt/sources.list > /dev/null <<EOT
        deb http://archive.ubuntu.com/ubuntu jammy main universe
        EOT
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.0-dev \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          libglib2.0-dev \
          libsoup-2.4-1 \
          libsoup2.4-dev \
          libjavascriptcoregtk-4.0-dev \
          libjavascriptcoregtk-4.1-dev

    # macOS-specific dependencies might be added here in the future
    # - name: Install macOS Dependencies
    #   if: runner.os == 'macOS' && (inputs.app_type == 'tauri' || inputs.app_type == 'tauri-v1')
    #   shell: bash
    #   run: |
    #     brew install xxxx

    # Windows-specific dependencies might be added here in the future
    # - name: Install Windows Dependencies
    #   if: runner.os == 'Windows' && (inputs.app_type == 'tauri' || inputs.app_type == 'tauri-v1')
    #   shell: bash
    #   run: |
    #     choco install xxxx
