[package]
name = "zubridge-middleware-node"
version = "0.1.0"
edition = "2021"
authors = ["Zubridge Contributors"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# NAPI-RS dependencies
napi = { version = "2.14.0", features = ["async"] }
napi-derive = "2.14.0"

# Zubridge middleware
zubridge-middleware = { path = "../" }

# Logging dependencies
fern = "0.6"
log = "0.4"
chrono = "0.4"

# JSON serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
