/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LoggingConfig {
  enabled?: boolean;
  websocketPort?: number;
  consoleOutput?: boolean;
  logLimit?: number;
  measurePerformance?: boolean;
  prettyPrint?: boolean;
  verbose?: boolean;
}
export interface ZubridgeMiddlewareConfig {
  logging?: LoggingConfig;
}
export interface Action {
  type: string;
  payload?: string;
}
export declare function initZubridgeMiddleware(
  config?: ZubridgeMiddlewareConfig | undefined | null,
): ZubridgeMiddleware;
/** Wrapper for Rust ZubridgeMiddleware to expose to JS */
export declare class ZubridgeMiddleware {
  processAction(action: Action): Promise<void>;
  getState(): Promise<string>;
  setState(stateJson: string): Promise<void>;
}
