name: Publish Release

on:
  workflow_call:
    inputs:
      target_branch:
        description: 'Target branch to release from'
        required: true
        type: string
      release_version:
        description: 'Release type (patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        type: string
      dry_run:
        description: 'Do not touch or write anything. Show the commands.'
        required: true
        default: false
        type: boolean
      branch_type:
        description: 'Branch type (main, feature)'
        required: true
        type: string
      packages:
        description: 'Packages to release (all, specific packages, or a comma-separated list)'
        required: false
        type: string
    secrets:
      github_bot_token:
        description: 'GitHub token for authentication'
        required: true
      npm_token:
        description: 'NPM token for publishing packages'
        required: true
      deploy_key:
        description: 'SSH deploy key for pushing to the repository'
        required: true
    outputs:
      release_tag:
        description: 'The created release tag'
        value: ${{ jobs.publish.outputs.release_tag }}

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.push_tags.outputs.release_tag }}
    steps:
      - name: ⚖️ Define target branch
        id: define
        env:
          TARGET_BRANCH: ${{ inputs.target_branch }}
          IS_MAJOR: ${{ contains(inputs.release_version, 'major') }}
          IS_PRE_RELEASE: ${{ contains(inputs.release_version, 'pre') }}
        run: |
          if [ "${IS_MAJOR}" == 'true' -a "${IS_PRE_RELEASE}" == 'false' ]; then
            echo "target_branch=main"
            echo "target_branch=main" >>"${GITHUB_OUTPUT}"
          else
            echo "target_branch=${TARGET_BRANCH}"
            echo "target_branch=${TARGET_BRANCH}" >>"${GITHUB_OUTPUT}"
          fi

      - name: 👷 Checkout branch for tagging
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.deploy_key }}
          # For major releases, we tag on main
          # For all other releases, we tag on the target branch
          ref: ${{steps.define.outputs.target_branch }}
          fetch-depth: 0 # Full history needed for versioning

      - name: 🛠️ Setup workspace
        uses: ./.github/workflows/actions/setup-workspace
        with:
          node-version: '20'

      - name: 🏗️ Build packages
        uses: ./.github/workflows/actions/build-verify

      - name: 📦 Configure NPM registry
        shell: bash
        run: |
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "DRY RUN: Would configure NPM registry for publishing"
          else
            # Set up NPM authentication for publishing
            pnpm set registry "https://registry.npmjs.org/"
            pnpm set //registry.npmjs.org/:_authToken ${{ secrets.npm_token }}
            pnpm whoami
          fi

      - name: 🏷️ Create Release and Tags
        # Uses turbo-version to bump versions and create git tags
        run: |
          # Ensure we're in the workspace root where version.config.json is located
          cd "$GITHUB_WORKSPACE"

          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            # Get the current version
            CURRENT_VERSION=$(jq -r '.version' packages/electron/package.json)
            echo "Current version: $CURRENT_VERSION"

            # Run turbo-version to calculate the next version
            # This will update package.json files but won't create git tags or push anything
            echo "Running turbo-version to calculate the next version..."
            pnpm turbo-version -b ${{ inputs.release_version }}

            # Get the new version that was calculated
            NEW_VERSION=$(jq -r '.version' packages/electron/package.json)
            echo "Next version would be: $NEW_VERSION"

            # Show what files were changed
            echo "Files that would be modified:"
            git diff --name-only

            # Show the actual changes
            echo "Changes that would be made:"
            git diff --color

            echo "DRY RUN: Would create release and tags with command: pnpm turbo-version -b ${{ inputs.release_version }}"
            echo "DRY RUN: Would bump version from $CURRENT_VERSION to $NEW_VERSION"
            echo "DRY RUN: Would create git tag v$NEW_VERSION"

            # Store the new version for later use
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

            # Reset changes made by turbo-version since this is a dry run
            git reset --hard HEAD
          else
            pnpm turbo-version -b ${{ inputs.release_version }}
            # Store the new version for later use
            NEW_VERSION=$(jq -r '.version' packages/electron/package.json)
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          fi

      - name: 📢 Publish to NPM
        shell: bash
        run: |
          # Use 'latest' tag for all releases
          TAG="latest"

          # Use 'next' tag for pre-releases
          if [[ "${{ contains(inputs.release_version, 'pre') }}" == "true" ]]; then
            TAG="next"
          fi

          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            # Get package names that would be published
            echo "DRY RUN: Would publish the following packages to NPM with tag '${TAG}':"
            PACKAGES=()
            while IFS= read -r pkg_json; do
              if [[ "$pkg_json" != *"node_modules"* ]]; then
                PKG_NAME=$(jq -r '.name' "$pkg_json")
                if [[ "$PKG_NAME" == @zubridge/* ]]; then
                  echo "  - $PKG_NAME@${NEW_VERSION}"
                  PACKAGES+=("$PKG_NAME")
                fi
              fi
            done < <(find packages -name "package.json" -maxdepth 2 -mindepth 2)

            echo "DRY RUN: Would publish to NPM with command: pnpx tsx scripts/publish.ts --tag ${TAG}"
          else
            if [[ "${{ github.repository }}" == "goosewobbler/zubridge" ]]; then
              # Set up the packages parameter if provided
              PACKAGE_ARG=""
              if [[ -n "${{ inputs.packages }}" ]]; then
                if [[ "${{ inputs.packages }}" == "all" ]]; then
                  # Release all packages
                  echo "Releasing all packages"
                else
                  # Always include core packages with specific packages
                  PACKAGE_ARG="--filter ${{ inputs.packages }}"
                  echo "Releasing specific packages: ${{ inputs.packages }} (including core dependencies)"
                fi
              else
                echo "Releasing all packages"
              fi
              pnpx tsx scripts/publish.ts --tag ${TAG} ${PACKAGE_ARG}
            else
              echo "Skipping actual publish because this is not the official repository"
            fi
          fi

      # Verify the published packages
      - name: 🔍 Verify published packages
        shell: bash
        env:
          PACKAGES: ${{ inputs.packages }}
        run: |
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "DRY RUN: Would verify packages were published correctly"
          else
            if [[ "${{ github.repository }}" == "goosewobbler/zubridge" ]]; then

              # Track overall verification status
              VERIFICATION_SUCCESS=true

              function check_npm_package() {
                local package_name=$1
                local expected_version=$2

                echo "Checking NPM for $package_name@$expected_version..."

                # Wait for NPM to index the package (up to 60 seconds)
                for i in {1..6}; do
                  if npm view "$package_name@$expected_version" version &>/dev/null; then
                    echo "✅ $package_name@$expected_version is available on NPM"
                    return 0
                  else
                    echo "Package not found on attempt $i, waiting 10 seconds..."
                    sleep 10
                  fi
                done

                echo "❌ Failed to find $package_name@$expected_version on NPM after 60 seconds"
                return 1
              }

              # Process packages based on filter
              if [[ "$PACKAGES" != "all" && "$PACKAGES" != "" ]]; then
                # Check only specified packages
                echo "Verifying specified packages..."
                IFS=',' read -ra PKG_LIST <<< "$PACKAGES"
                for pkg_name in "${PKG_LIST[@]}"; do
                  pkg_name=$(echo "$pkg_name" | xargs) # Trim whitespace
                  PKG_DIR="packages/$(echo $pkg_name | cut -d'/' -f2)"
                  if [[ -f "$PKG_DIR/package.json" ]]; then
                    PKG_VERSION=$(jq -r '.version' "$PKG_DIR/package.json")
                    PKG_FULL_NAME=$(jq -r '.name' "$PKG_DIR/package.json")
                    if ! check_npm_package "$PKG_FULL_NAME" "$PKG_VERSION"; then
                      VERIFICATION_SUCCESS=false
                      echo "::error::Package verification failed for $PKG_FULL_NAME@$PKG_VERSION"
                    fi
                  else
                    echo "⚠️ Warning: Package $pkg_name not found at $PKG_DIR"
                    VERIFICATION_SUCCESS=false
                    echo "::error::Package directory not found for $pkg_name"
                  fi
                done
              else
                # Check all packages
                echo "Verifying all packages..."
                while IFS= read -r pkg_json; do
                  if [[ "$pkg_json" != *"node_modules"* ]]; then
                    PKG_NAME=$(jq -r '.name' "$pkg_json")
                    if [[ "$PKG_NAME" == @zubridge/* ]]; then
                      PKG_VERSION=$(jq -r '.version' "$pkg_json")
                      if ! check_npm_package "$PKG_NAME" "$PKG_VERSION"; then
                        VERIFICATION_SUCCESS=false
                        echo "::error::Package verification failed for $PKG_NAME@$PKG_VERSION"
                      fi
                    fi
                  fi
                done < <(find packages -name "package.json" -maxdepth 2 -mindepth 2)
              fi

              echo "Package verification complete"

              # Exit with error code if any package verification failed
              if [[ "$VERIFICATION_SUCCESS" != "true" ]]; then
                echo "::error::One or more packages failed verification"
                exit 1
              fi

              echo "All packages verified successfully"
            else
              echo "Skipping verification because this is not the official repository"
            fi
          fi

      - name: 🚀 Push Tags and Commits
        id: push_tags
        shell: bash
        run: |
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            RELEASE_TAG="v${NEW_VERSION}"
            echo "DRY RUN: Would push tags and commits to remote repository"
            echo "DRY RUN: Would push tag $RELEASE_TAG"
            echo "DRY RUN: Would push branch ${{ inputs.target_branch }}"

            # For dry run, set the calculated release tag for downstream jobs
            echo "release_tag=$RELEASE_TAG" >>"${GITHUB_OUTPUT}"
            echo "DRY RUN: Set release_tag output to $RELEASE_TAG for downstream jobs"
          else
            echo "Git log:"
            git log --oneline -n 5
            # Get the most recent tag (the one we just created)
            RELEASE_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "Release tag: ${RELEASE_TAG}"
            echo "Pushing tags and commits..."
            # Push tags and commits without running the pre-push hook
            git push --tags --no-verify && git push --no-verify
            # Pass the release tag to the next step
            echo "release_tag=${RELEASE_TAG}" >>"${GITHUB_OUTPUT}"
          fi

      - name: 📝 Create GitHub Release
        if: ${{ !inputs.dry_run }}
        uses: softprops/action-gh-release@v2
        with:
          draft: true # Create as draft for manual review
          generate_release_notes: true
          prerelease: ${{ contains(inputs.release_version, 'pre') }}
          repository: ${{ github.repository }}
          tag_name: ${{ steps.push_tags.outputs.release_tag }}
          token: ${{ secrets.github_bot_token }}

      - name: 📋 Log GitHub Release (dry run only)
        if: ${{ inputs.dry_run }}
        run: |
          RELEASE_TAG="v${NEW_VERSION}"
          echo "DRY RUN: Would create a GitHub release with:"
          echo "  - Tag name: $RELEASE_TAG"
          echo "  - Draft: true"
          echo "  - Generate release notes: true"
          echo "  - Prerelease: ${{ contains(inputs.release_version, 'pre') }}"
          echo "  - Repository: ${{ github.repository }}"
          echo "  - Title: Release $RELEASE_TAG"
