name: Calculate Release Branches

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch type to release from (feature, main)'
        required: true
        type: string
      release_version:
        description: 'Release type (patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        type: string
    outputs:
      target_branch:
        description: 'Resolved target branch name'
        value: ${{ jobs.calculate.outputs.target_branch }}
      next_version_branch:
        description: 'Next feature branch name for major releases'
        value: ${{ jobs.calculate.outputs.next_version_branch }}

jobs:
  # Validate release parameters
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check Release Parameters
        env:
          IS_MAJOR: ${{ contains(inputs.release_version, 'major') }}
          IS_FEATURE: ${{ inputs.branch == 'feature' }}
        run: |
          # Ensure major releases only happen from feature branches
          if [ "${IS_MAJOR}" == 'true' -a "${IS_FEATURE}" == 'false' ]; then
            echo "::error::Major releases must come from feature branches"
            exit 1
          fi

  # Calculate version numbers and determine target branches
  calculate:
    runs-on: 'ubuntu-latest'
    outputs:
      target_branch: ${{ steps.define_branches.outputs.target_branch }}
      next_version_branch: ${{ steps.define_branches.outputs.next_version_branch }}
    needs: ['check']
    steps:
      - name: 👷 Checkout repository
        uses: actions/checkout@v4
        with:
          # Always checkout main first to calculate the target branch
          ref: 'main'

      - name: 🧮 Calculate version numbers
        id: calculate_versions
        shell: bash
        env:
          BRANCH_TYPE: ${{ inputs.branch }}
          RELEASE_TYPE: ${{ inputs.release_version }}
        run: |
          # Find the first package.json file in the packages directory
          FIRST_PKG_JSON=$(find packages -name "package.json" -type f -not -path "*/node_modules/*" | sort | head -n 1)

          if [ -z "$FIRST_PKG_JSON" ]; then
            echo "::error::Could not find any package.json files in the packages directory"
            exit 1
          fi

          # Get package details
          PKG_NAME=$(cat "${FIRST_PKG_JSON}" | jq -r '.name')
          PKG_VERSION=$(cat "${FIRST_PKG_JSON}" | jq -r '.version')

          echo "Using package for version calculation: ${PKG_NAME} (${PKG_VERSION})"

          # Parse version components
          CURRENT_VERSION=$PKG_VERSION
          CURRENT_MAJOR_VERSION=$(echo $CURRENT_VERSION | cut -d. -f1)
          CURRENT_MINOR_VERSION=$(echo $CURRENT_VERSION | cut -d. -f2)
          CURRENT_PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d. -f3 | cut -d- -f1)

          echo "current-version=${CURRENT_VERSION}"
          echo "current-major-version=${CURRENT_MAJOR_VERSION}"
          echo "current-minor-version=${CURRENT_MINOR_VERSION}"
          echo "current-patch-version=${CURRENT_PATCH_VERSION}"

          echo "current-version=${CURRENT_VERSION}" >>"${GITHUB_OUTPUT}"
          echo "current-major-version=${CURRENT_MAJOR_VERSION}" >>"${GITHUB_OUTPUT}"
          echo "current-minor-version=${CURRENT_MINOR_VERSION}" >>"${GITHUB_OUTPUT}"
          echo "current-patch-version=${CURRENT_PATCH_VERSION}" >>"${GITHUB_OUTPUT}"

          # For pre-1.0 versions, the next major version is still 1
          # This ensures feature branches are named correctly
          if [ "${CURRENT_MAJOR_VERSION}" -eq "0" ]; then
            FEATURE_MAJOR_VERSION="1"
          else
            FEATURE_MAJOR_VERSION="$((CURRENT_MAJOR_VERSION + 1))"
          fi

          echo "feature-major-version=${FEATURE_MAJOR_VERSION}"
          echo "feature-major-version=${FEATURE_MAJOR_VERSION}" >>"${GITHUB_OUTPUT}"

      - name: 🎯 Define target branch names
        id: define_branches
        shell: bash
        env:
          BRANCH_TYPE: ${{ inputs.branch }}
          CURRENT_MAJOR_VERSION: ${{ steps.calculate_versions.outputs.current-major-version}}
          FEATURE_MAJOR_VERSION: ${{ steps.calculate_versions.outputs.feature-major-version}}
        run: |
          if [ "${BRANCH_TYPE}" == 'feature' ]; then
            # For feature branches, use as-is
            echo "target_branch=feature/v${FEATURE_MAJOR_VERSION}.x"
            echo "target_branch=feature/v${FEATURE_MAJOR_VERSION}.x" >> $GITHUB_OUTPUT
          else
            # For main, use as-is
            echo "target_branch=${BRANCH_TYPE}" >> $GITHUB_OUTPUT
          fi

          # The next version branch will be for the next major version
          echo "next_version_branch=feature/v${FEATURE_MAJOR_VERSION}.x"
          echo "next_version_branch=feature/v${FEATURE_MAJOR_VERSION}.x" >>"${GITHUB_OUTPUT}"

      - name: 🔍 Verify branch exists
        shell: bash
        env:
          BRANCH_TYPE: ${{ inputs.branch }}
          TARGET_BRANCH: ${{ steps.define_branches.outputs.target_branch }}
        run: |
          echo "Verifying branch: ${TARGET_BRANCH}"

          # Check if branch exists remotely
          if ! git ls-remote --heads origin "${TARGET_BRANCH}" | grep -q "${TARGET_BRANCH}"; then
            if [ "${BRANCH_TYPE}" == "feature" ]; then
              echo "::error::Feature branch '${TARGET_BRANCH}' does not exist. Please create this branch first or specify a different branch."
              echo "::error::Expected branch naming convention: feature/v{next_major_version} (e.g., feature/v2.x)"
            else
              echo "::error::Branch '${TARGET_BRANCH}' does not exist."
            fi
            exit 1
          fi

          echo "✅ Branch '${TARGET_BRANCH}' exists and is valid"
