name: Publish Release

on:
  workflow_call:
    inputs:
      target_branch:
        description: 'Target branch to release from'
        required: true
        type: string
      release_version:
        description: 'Release type (patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        type: string
      dry_run:
        description: 'Do not touch or write anything. Show the commands.'
        required: true
        default: false
        type: boolean
      branch_type:
        description: 'Branch type (main, feature)'
        required: true
        type: string
      packages:
        description: 'Package directory name(s) to release (specific directories, or a comma-separated list)'
        required: false
        type: string
    secrets:
      github_bot_token:
        description: 'GitHub token for authentication'
        required: true
      npm_token:
        description: 'NPM token for publishing packages'
        required: true
      deploy_key:
        description: 'SSH deploy key for pushing to the repository'
        required: true
      crates_io_token:
        description: 'Crates.io token for publishing Rust crates'
        required: true
    outputs:
      release_tag:
        description: 'The created release tag'
        value: ${{ jobs.publish.outputs.release_tag }}

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.push_tags.outputs.release_tag }}
    steps:
      - name: 👷 Checkout target branch for release
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.deploy_key }}
          # Always checkout the actual target branch passed from calculate job
          ref: ${{ inputs.target_branch }}
          fetch-depth: 0 # Full history needed for versioning

      - name: 🛠️ Setup workspace
        uses: ./.github/workflows/actions/setup-workspace
        with:
          node-version: '20'

      - name: 🏗️ Build packages
        uses: ./.github/workflows/actions/build-verify

      - name: 📦 Configure NPM registry
        shell: bash
        run: |
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "DRY RUN: Would configure NPM registry for publishing"
          else
            # Set up NPM authentication for publishing
            pnpm set registry "https://registry.npmjs.org/"
            pnpm set //registry.npmjs.org/:_authToken ${{ secrets.npm_token }}
            pnpm whoami
          fi

      - name: 🔄 Calculate version & create tag
        id: versioning
        run: pnpx tsx .github/workflows/scripts/calculate-version.ts
        env:
          # Pass inputs as environment variables, prefixed with INPUT_
          INPUT_PACKAGES: ${{ inputs.packages }}
          INPUT_RELEASE_VERSION: ${{ inputs.release_version }}
          INPUT_DRY_RUN: ${{ inputs.dry_run }}
          # GITHUB_WORKSPACE is automatically available

      - name: 📢 Publish to NPM
        shell: bash
        id: npm_publish
        continue-on-error: true
        # Skip NPM publish for Rust-only packages
        if: ${{ !contains(fromJson('["tauri-plugin"]'), inputs.packages) }}
        run: |
          # Get the new version from the previous step's output
          NEW_VERSION="${{ steps.versioning.outputs.new_version }}"
          if [[ -z "$NEW_VERSION" ]]; then
            echo "::error::Failed to get NEW_VERSION from the versioning step."
            exit 1
          fi
          echo "Retrieved NEW_VERSION: $NEW_VERSION"

          # Get NPM tag based on version
          if [[ "$NEW_VERSION" =~ -(beta|alpha|rc|next|pre)[\.0-9]*$ ]]; then
            TAG="next"
          else
            TAG="latest"
          fi
          echo "Using NPM tag: $TAG"

          # Helper function to get package name from directory name
          get_pkg_name() {
            local pkg_dir="$1"
            # Read the package name from package.json
            if [[ -f "packages/$pkg_dir/package.json" ]]; then
              jq -r '.name' "packages/$pkg_dir/package.json"
            else
              echo "::error::Package.json not found for directory: packages/$pkg_dir"
              exit 1
            fi
          }

          # Helper function to check if package directory exists
          check_pkg_dir_exists() {
            local pkg_dir="$1"
            if [[ -f "packages/$pkg_dir/package.json" ]]; then
              return 0 # Exists as direct package
            elif [[ -d "packages/$pkg_dir" ]]; then
              # If it's a directory, search for nested package.json files one level down
              for nested_dir in packages/$pkg_dir/*/; do
                if [[ -f "${nested_dir}package.json" ]]; then
                  return 0 # Exists as nested package
                fi
              done
            fi

            return 1 # Doesn't exist
          }

          # For dry run, just echo what would happen
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "DRY RUN: Would publish packages to NPM with tag '$TAG'"

            if [[ "${{ inputs.packages }}" == *","* ]]; then
              # For custom package list (directory names)
              IFS=',' read -ra PKG_LIST <<< "${{ inputs.packages }}"
              hasPublishedPackages=false
              for pkg_dir in "${PKG_LIST[@]}"; do
                pkg_dir=$(echo "$pkg_dir" | xargs) # Trim whitespace
                if check_pkg_dir_exists "$pkg_dir"; then
                   pkg_name=$(get_pkg_name "$pkg_dir")
                   echo "Would publish $pkg_dir package ($pkg_name) with tag $TAG"
                   hasPublishedPackages=true
                else
                   # Standardized warning/error format
                   echo "::warning::[DRY RUN] Package directory 'packages/$pkg_dir' not found."
                fi
              done
            else
              if check_pkg_dir_exists "${{ inputs.packages }}"; then
                 pkg_name=$(get_pkg_name "${{ inputs.packages }}")
                 echo "Would publish ${{ inputs.packages }} package ($pkg_name) with tag $TAG"
              else
                 echo "::warning::[DRY RUN] Package directory 'packages/${{ inputs.packages }}' not found."
              fi
            fi

            # Set publish status to success for dry run
            echo "publish_status=success" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Actual publish
          PUBLISH_EXIT_CODE=0
          if [[ "${{ inputs.packages }}" == *","* ]]; then
            # Handle custom package list
            FILTER_CMD=""
            IFS=',' read -ra PKG_LIST <<< "${{ inputs.packages }}"
            for pkg_dir in "${PKG_LIST[@]}"; do
              pkg_dir=$(echo "$pkg_dir" | xargs) # Trim whitespace

              if [[ -f "packages/$pkg_dir/package.json" ]]; then
                # Standard package
                FILTER_CMD="$FILTER_CMD --filter=./packages/$pkg_dir"
              elif [[ -d "packages/$pkg_dir" ]]; then
                # Check for nested package.json files
                FOUND_NESTED=false
                for nested_dir in packages/$pkg_dir/*/; do
                  if [[ -f "${nested_dir}package.json" ]]; then
                    # Found a nested package
                    nested_path=${nested_dir%/} # Remove trailing slash
                    FILTER_CMD="$FILTER_CMD --filter=./${nested_path}"
                    FOUND_NESTED=true
                  fi
                done

                if [[ "$FOUND_NESTED" == "false" ]]; then
                  echo "::error::Error: No package.json found in or under 'packages/$pkg_dir'. Aborting publish."
                  exit 1
                fi
              else
                echo "::error::Error: Package directory 'packages/$pkg_dir' not found. Aborting publish."
                exit 1
              fi
            done
            pnpx tsx scripts/publish.ts --tag=$TAG $FILTER_CMD || PUBLISH_EXIT_CODE=$?
          else
            # Single package case
            pkg_dir="${{ inputs.packages }}"

            # Find all publishable packages, including nested ones
            if [[ -f "packages/$pkg_dir/package.json" ]]; then
              # Standard package
              pkg_path="./packages/$pkg_dir"
              pnpx tsx scripts/publish.ts --tag=$TAG --filter=$pkg_path || PUBLISH_EXIT_CODE=$?
            elif [[ -d "packages/$pkg_dir" ]]; then
              # Check for nested package.json files
              FOUND_NESTED=false
              for nested_dir in packages/$pkg_dir/*/; do
                if [[ -f "${nested_dir}package.json" ]]; then
                  # Found a nested package
                  nested_path=${nested_dir%/} # Remove trailing slash
                  pnpx tsx scripts/publish.ts --tag=$TAG --filter=./${nested_path} || PUBLISH_EXIT_CODE=$?
                  FOUND_NESTED=true
                fi
              done

              if [[ "$FOUND_NESTED" == "false" ]]; then
                echo "::error::Error: No package.json found in or under 'packages/$pkg_dir'. Aborting publish."
                exit 1
              fi
            else
              echo "::error::Package directory ./packages/$pkg_dir does not exist"
              exit 1
            fi
          fi

          # Check if we had an "already published" error
          if [[ $PUBLISH_EXIT_CODE -ne 0 ]]; then
            # Check if the error was due to the package already being published
            if grep -q "already exists$\|already published$" <<< "$(pnpm view @zubridge/${{ inputs.packages }}@$NEW_VERSION 2>&1)" || grep -q "already exists$\|already published$" <<< "$(pnpm view @zubridge/${{ inputs.packages }}@$NEW_VERSION 2>&1)"; then
              echo "::warning::Package @zubridge/${{ inputs.packages }}@$NEW_VERSION is already published to npm. Continuing with the workflow."
              echo "publish_status=already_published" >> $GITHUB_OUTPUT
              # Set exit code to 0 to allow workflow to continue
              exit 0
            else
              # This was a real error, not just "already published"
              echo "::error::Failed to publish package. Error code: $PUBLISH_EXIT_CODE"
              echo "publish_status=failed" >> $GITHUB_OUTPUT
              exit $PUBLISH_EXIT_CODE
            fi
          else
            echo "publish_status=success" >> $GITHUB_OUTPUT
          fi
        env:
          # Pass the new version needed by the publish script (if it reads env vars)
          # Or preferably, modify publish.ts to accept version as an argument
          NEW_VERSION: ${{ steps.versioning.outputs.new_version }}

      - name: 🔍 Verify published NPM packages
        shell: bash
        if: ${{ !contains(fromJson('["tauri-plugin"]'), inputs.packages) && (inputs.dry_run == 'true' || steps.npm_publish.outputs.publish_status != 'failed') }}
        run: bash .github/workflows/scripts/verify-published.sh
        env:
          # Pass necessary variables to the script environment
          INPUT_PACKAGES: ${{ inputs.packages }}
          INPUT_DRY_RUN: ${{ inputs.dry_run }}
          NEW_VERSION: ${{ steps.versioning.outputs.new_version }}
          # GITHUB_WORKSPACE is automatically available

      # Only publish Rust crates when explicitly selected
      - name: 🦀 Set up Rust
        if: ${{ contains(fromJson('["tauri-plugin", "middleware"]'), inputs.packages) && (inputs.dry_run == 'true' || steps.npm_publish.outputs.publish_status != 'failed') }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: 🔧 Login to crates.io
        if: ${{ contains(fromJson('["tauri-plugin", "middleware"]'), inputs.packages) && inputs.dry_run != 'true' }}
        run: |
          cargo login ${{ secrets.crates_io_token }}

      - name: 📦 Publish Rust crates to crates.io
        if: ${{ contains(fromJson('["tauri-plugin", "middleware"]'), inputs.packages) }}
        run: |
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "DRY RUN: Would publish Rust crates to crates.io"
            pnpx tsx scripts/publish-crates.ts --dry-run "${{ inputs.packages }}"
          else
            pnpx tsx scripts/publish-crates.ts "${{ inputs.packages }}"
          fi

      - name: 🔍 Verify published Rust crates
        shell: bash
        if: ${{ contains(fromJson('["tauri-plugin", "middleware"]'), inputs.packages) && inputs.dry_run != 'true' }}
        run: bash .github/workflows/scripts/verify-crates-published.sh
        env:
          # Pass necessary variables to the script environment
          INPUT_PACKAGES: ${{ inputs.packages }}
          INPUT_DRY_RUN: ${{ inputs.dry_run }}
          NEW_VERSION: ${{ steps.versioning.outputs.new_version }}
          # GITHUB_WORKSPACE is automatically available

      - name: 🚀 Push Tags and Commits
        id: push_tags
        shell: bash
        run: |
          # Get the new version from the versioning step's output
          NEW_VERSION="${{ steps.versioning.outputs.new_version }}"
          if [[ -z "$NEW_VERSION" ]]; then
             echo "::error::Failed to get NEW_VERSION from the versioning step."
             exit 1
          fi

          # Define the primary release tag for GitHub releases
          RELEASE_TAG="v${NEW_VERSION}"
          echo "Using version for tagging: $NEW_VERSION (release tag: $RELEASE_TAG)"

          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            echo "DRY RUN: Would push tags created by package-versioner"
            echo "DRY RUN: Would push branch ${{ inputs.target_branch }}"
            echo "release_tag=${RELEASE_TAG}" >> "${GITHUB_OUTPUT}"
          else
            echo "Git log before push:"
            git log --oneline -n 5

            echo "Pushing tags and commits created by package-versioner..."
            git push --tags --no-verify
            git push origin "${{ inputs.target_branch }}" --no-verify

            echo "release_tag=${RELEASE_TAG}" >> "${GITHUB_OUTPUT}"
            echo "Successfully pushed tags and commits"
          fi

      - name: 📝 Create GitHub Releases
        if: ${{ !inputs.dry_run }}
        run: |
          # Create the main release
          echo "Creating main GitHub release with tag ${{ steps.push_tags.outputs.release_tag }}"
          gh release create "${{ steps.push_tags.outputs.release_tag }}" \
            --draft \
            --generate-notes \
            --title "Release ${{ steps.push_tags.outputs.release_tag }}" \
            ${{ contains(inputs.release_version, 'pre') && '--prerelease' || '' }}
        env:
          GH_TOKEN: ${{ secrets.github_bot_token }}

      - name: 📋 Log GitHub Release (dry run only)
        if: ${{ inputs.dry_run }}
        run: |
          echo "DRY RUN: Would create a GitHub release with:"
          echo "  - Tag name: ${{ steps.push_tags.outputs.release_tag }}"
          echo "  - Draft: true"
          echo "  - Generate release notes: true"
          echo "  - Prerelease: ${{ contains(inputs.release_version, 'pre') }}"
          echo "  - Repository: ${{ github.repository }}"
          echo "  - Title: Release ${{ steps.push_tags.outputs.release_tag }}"

      - name: Export TAG for reference in debug outputs
        if: ${{ !inputs.dry_run }}
        run: echo "TAG=$TAG" >> $GITHUB_ENV
