name: 'Handle Logs'
description: 'Displays and uploads logs'
inputs:
  os:
    description: 'Operating system of the runner'
    required: true
  app:
    description: 'Type of application (electron, tauri, tauri-v1) or package-test'
    required: true
  mode:
    description: 'Application mode (basic, handlers, etc.)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Show E2E Test Logs
      if: inputs.app == 'electron'
      run: |
        echo "=== E2E Test Logs for ${{ inputs.app }}-${{ inputs.mode }} ==="
        
        LOG_DIR="./e2e/wdio-logs-${{ inputs.app }}/e2e-${{ inputs.mode }}"
        
        if [ -d "$LOG_DIR" ]; then
          # Find and display all log files in the directory
          find "$LOG_DIR" -name "*.log" -type f | sort | while read -r log_file; do
            log_name=$(basename "$log_file")
            echo "::group::📄 $log_name"
            echo "=== Contents of $log_name ==="
            cat "$log_file" || echo "Could not read log file: $log_file"
            echo "::endgroup::"
            echo ""
          done
        else
          echo "No log directory found at: $LOG_DIR"
        fi
        
        echo "=== End of E2E Test Logs ==="
      shell: bash

    - name: Show Package Test Logs
      if: inputs.app == 'package-test'
      run: |
        echo "=== Package Test Logs for ${{ inputs.mode }} ==="

        # Find all wdio-logs directories in apps
        find apps -name "wdio-logs-*" -type d | sort | while read -r log_dir; do
          app_name=$(basename "$log_dir" | sed 's/wdio-logs-//')
          echo "::group::🔧 Logs for $app_name"

          # Find and display all log files in the directory
          find "$log_dir" -name "*.log" -type f | sort | while read -r log_file; do
            log_name=$(basename "$log_file")
            echo "::group::📄 $log_name"
            echo "=== Contents of $log_name ==="
            cat "$log_file" || echo "Could not read log file: $log_file"
            echo "::endgroup::"
            echo ""
          done
          
          echo "::endgroup::"
        done

        echo "=== End of Package Test Logs ==="
      shell: bash

    - name: Upload E2E Test Logs
      uses: actions/upload-artifact@v4
      if: inputs.app == 'electron'
      with:
        name: e2e-logs-${{ inputs.os }}-${{ inputs.app }}-${{ inputs.mode }}
        path: e2e/wdio-logs-${{ inputs.app }}/e2e-${{ inputs.mode }}/*.log
        retention-days: 30
        if-no-files-found: warn

    - name: Upload Package Test Logs
      uses: actions/upload-artifact@v4
      if: inputs.app == 'package-test'
      with:
        name: package-test-logs-${{ inputs.os }}-${{ inputs.mode }}
        path: apps/*/wdio-logs-*
        retention-days: 30
        if-no-files-found: warn
